### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by manniemarlon** [JoelLogan/Infinity-Gauntlet#15]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'infinitygauntlet'!
exit code -1
anyone know how to fix this?

**Comment by JoelLogan** [comment]
@manniemarlon Can you paste the log file from that run, so that I have more information about where it crashed? Use https://mclo.gs/

**Comment by manniemarlon** [comment]
https://mclo.gs/y4ST65d

**Comment by JoelLogan** [comment]
Please update your fabric-api version. I'm using the loot-v3 library from the 0.100.5 and above version of API, and the 0.100.4 version of the API doesn't have that library.

**Comment by manniemarlon** [comment]
so when i go to fabric downloader i select 0.16.0 for loader version?

**Comment by manniemarlon** [comment]
nvm fixed it!

**Comment by JoelLogan** [comment]
Great!
